# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [6]:
print (np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saiteja/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/saiteja/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saiteja/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

#### 3. Create a null vector of size 10

In [17]:
arr=np.zeros(10)
print (arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [19]:
x=arr.size
y=arr.itemsize
print('Memory size=',x*y)

Memory size= 80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [26]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [27]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [33]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [47]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr[ : :-1]

array([[ 3. , -7. ,  4. ,  2. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 4. , -0.5,  6. ,  0. ],
       [-1. ,  2. ,  0. ,  4. ]])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [51]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [53]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [54]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [57]:
np.random.random((3,3,3))

array([[[0.46880615, 0.062038  , 0.49706628],
        [0.10207489, 0.97213696, 0.47474129],
        [0.23356354, 0.0563613 , 0.11258443]],

       [[0.07578088, 0.62641862, 0.87404999],
        [0.80104535, 0.88756954, 0.22737654],
        [0.09379231, 0.08488017, 0.60140826]],

       [[0.4216186 , 0.78708548, 0.49727579],
        [0.75577285, 0.49351167, 0.7555476 ],
        [0.55776785, 0.63852254, 0.35811795]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [63]:
arr=np.random.random((10,10))
print(arr)
print(arr.min())
print(arr.max())

[[0.71416687 0.06078982 0.34367521 0.74300524 0.09819052 0.87253595
  0.84169367 0.61153173 0.66059891 0.90499843]
 [0.05541964 0.14562442 0.24621606 0.75540174 0.4507523  0.06888248
  0.53580906 0.6942055  0.6506343  0.48141142]
 [0.71858494 0.99468905 0.79285851 0.57342134 0.30888812 0.31333537
  0.45197148 0.54267422 0.30917069 0.7071335 ]
 [0.76613757 0.98781821 0.57638085 0.89082542 0.86090429 0.73348312
  0.93933119 0.5116386  0.83531236 0.30194083]
 [0.50205999 0.68610298 0.55451051 0.48055248 0.35365638 0.66050975
  0.03887005 0.83451309 0.17950804 0.05018456]
 [0.86746157 0.1690678  0.0489395  0.44001882 0.11159466 0.90980068
  0.8940637  0.37612486 0.66081907 0.29022413]
 [0.21125217 0.51262124 0.34874842 0.06502667 0.09268794 0.13992199
  0.95190175 0.71265827 0.79123717 0.08464988]
 [0.63352863 0.30596111 0.09977737 0.59108782 0.33182474 0.14352631
  0.93373526 0.71300572 0.00631055 0.22126928]
 [0.58077391 0.35843032 0.80884855 0.81860622 0.9966106  0.36950053
  0.87280379

#### 14. Create a random vector of size 30 and find the mean value

In [69]:
arr=np.random.random((30))
print(arr)
print(np.mean(arr))

[0.46604558 0.85227176 0.1527343  0.37777294 0.71760349 0.69525485
 0.43224613 0.5821399  0.03027052 0.07012456 0.14907724 0.72255767
 0.51607155 0.18255693 0.24810392 0.62724014 0.41442088 0.42783955
 0.18010362 0.45038101 0.83284637 0.6172779  0.87432948 0.08323465
 0.93180423 0.64802227 0.09736125 0.20925987 0.10100521 0.77947924]
0.4489812333615688


#### 15. Create a 2d array with 1 on the border and 0 inside

In [73]:
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print(arr)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [81]:
arr=np.random.random((3,3))
x=np.pad(arr,pad_width=1,mode='constant',constant_values=0)
print(x)

[[0.         0.         0.         0.         0.        ]
 [0.         0.00218132 0.73375281 0.78859312 0.        ]
 [0.         0.59323816 0.94936097 0.60376015 0.        ]
 [0.         0.26181234 0.28395662 0.46988165 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [83]:
arr=np.diag(1+np.arange(4),k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [86]:
arr=np.ones((8,8))
arr[ : :2, : :2]=0
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [88]:
arr=np.unravel_index(100,shape=(6,7,8))
arr

(1, 5, 4)